image: Visual Studio 2017

branches:
  only:
  - master

clone_depth: 5

version: 0.7.{build}

platform:
  - x86
  - x64
  
configuration:
  - Release

build:
  project: memhunter.sln 
  verbosity: minimal
  parallel: true

artifacts:
  - path: 'C:\projects\memhunter\build\**\*.dll'
  - path: 'C:\projects\memhunter\build\**\*.exe'
  - path: 'C:\projects\memhunter\build\**\*.lib'
