image: Visual Studio 2017

branches:
  only:
  - master

clone_depth: 5

version: 0.7.{build}

platform:
  - x86
  - x64
  
configuration:
  - Release

build:
  project: memhunter.sln 
  verbosity: minimal
  parallel: true

artifacts:
  - path: '.\build\**\*.dll'
  - path: '.\build\**\*.exe'
  - path: '.\build\**\*.lib'
